import { useState } from "react";
import BallotQuestion from "./components/ballot-question";
import ContentSchemata from "./components/content-schemata";
import ConceptH from "./components/concept-h";
import ConceptRentControl from "./components/concept-rent-control";

const CONCEPTS = [
  // Concept D temporarily hidden
  // {
  //   id: "D",
  //   label: "Ballot Question",
  //   sub: "B2 Design",
  //   desc: "Ballot question detail page with tabbed navigation for Overview, Background, For & Against, etc.",
  // },
  {
    id: "E",
    label: "Content Schemata",
    sub: "Inventory View",
    desc: "Content inventory organized by tab — showing all content types and sources per section.",
  },
  {
    id: "H",
    label: "For & Against Example",
    sub: "Hybrid Approach",
    desc: "For & Against tab: Arguments synthesis, cross-cutting analysis, then research evidence.",
  },
  {
    id: "I",
    label: "Rent Control Example",
    sub: "Real Content Example",
    desc: "Rent control example",
  },
];

export default function App() {
  const [active, setActive] = useState("E");

  return (
    <div className="min-h-screen bg-background">
      {/* Fixed concept switcher strip */}
      <div
        className="fixed top-0 left-0 right-0 z-50 flex items-center gap-0 border-b"
        style={{
          backgroundColor: "#fff",
          borderColor: "#d1d1d1",
          height: 48,
          paddingLeft: 16,
          paddingRight: 16,
        }}
      >
        <span
          className="mr-5 shrink-0"
          style={{ fontFamily: "Nunito", fontWeight: 700, fontSize: 12, color: "#888", textTransform: "uppercase", letterSpacing: "0.1em" }}
        >
          IA Concepts
        </span>
        <div className="flex gap-2 flex-1 min-w-0 overflow-x-auto scrollbar-hide">
          {CONCEPTS.map((c) => {
            const isActive = active === c.id;
            return (
              <button
                key={c.id}
                onClick={() => setActive(c.id)}
                className="flex items-center gap-2 px-4 h-8 rounded transition-all whitespace-nowrap shrink-0"
                style={{
                  fontFamily: "Nunito",
                  fontWeight: 700,
                  fontSize: 13,
                  backgroundColor: isActive ? "#12266f" : "#f0f0f0",
                  color: isActive ? "#fff" : "#334156",
                  border: isActive ? "none" : "1px solid #d1d1d1",
                }}
              >
                <span
                  className="w-5 h-5 rounded-full flex items-center justify-center text-xs shrink-0"
                  style={{
                    backgroundColor: isActive ? "rgba(255,255,255,0.2)" : "#d1d1d1",
                    color: isActive ? "#fff" : "#606060",
                    fontFamily: "Nunito",
                    fontWeight: 800,
                    fontSize: 10,
                  }}
                >
                  {c.id}
                </span>
                {c.label}
                <span
                  className="hidden sm:inline ml-0.5"
                  style={{ fontWeight: 400, opacity: 0.75, fontSize: 12 }}
                >
                  — {c.sub}
                </span>
              </button>
            );
          })}
        </div>

        {/* Description */}
        <div className="hidden lg:flex items-center ml-6 shrink-0">
          <span style={{ fontFamily: "Nunito", fontSize: 12, color: "#606060" }}>
            {CONCEPTS.find((c) => c.id === active)?.desc}
          </span>
        </div>
      </div>

      {/* Concept content — offset for the strip */}
      <div style={{ paddingTop: 48 }}>
        {/* Concept D temporarily hidden: {active === "D" && <BallotQuestion />} */}
        {active === "E" && <ContentSchemata />}
        {active === "H" && (
          <>
            {/* Disclaimer — sticky below concept switcher, content scrolls under it */}
            <div className="sticky top-[48px] z-40 h-[37px] bg-[#fef3c7] border-b border-[#f59e0b] px-[16px] flex items-center gap-[8px]">
              <span className="text-[16px]">⚠️</span>
              <p className="font-['Nunito'] font-bold text-[13px] text-[#92400e] leading-[1.4]">
                All content in the For & Against Example, including campaign positions, research citations, and AI synthesis, was generated by AI for demonstration purposes only. This is not real ballot measure data.
              </p>
            </div>
            <ConceptH />
          </>
        )}
        {active === "I" && (
          <>
            {/* Disclaimer */}
            <div className="sticky top-[48px] z-40 h-[37px] bg-[#fef3c7] border-b border-[#f59e0b] px-[16px] flex items-center gap-[8px]">
              <span className="text-[16px]">⚠️</span>
              <p className="font-['Nunito'] font-bold text-[13px] text-[#92400e] leading-[1.4]">
                This initiative was removed from the November 2026 ballot by the Massachusetts Supreme Judicial Court on June 23, 2026. Content is sourced from Ballotpedia and Massachusetts official government sources. Displayed as if it were on the ballot for prototype purposes.
              </p>
            </div>
            <ConceptRentControl />
          </>
        )}
      </div>
    </div>
  );
}
